/*
 * Copyright 2000-2025 Vaadin Ltd.
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License. You may obtain a copy of
 * the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations under
 * the License.
 */
package com.vaadin.hilla.engine;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;
import java.util.Optional;
import java.util.concurrent.atomic.AtomicReference;

import io.swagger.v3.oas.models.OpenAPI;
import org.jspecify.annotations.NonNull;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import com.vaadin.hilla.engine.commandrunner.CommandNotFoundException;
import com.vaadin.hilla.engine.commandrunner.CommandRunnerException;
import com.vaadin.hilla.generator.typescript.OutputFolder;
import com.vaadin.hilla.parser.core.OpenAPIFileType;

public final class GeneratorProcessor {
    public static String GENERATED_FILE_LIST_NAME = OutputFolder.FILE_LIST;

    /**
     * The property which puts the Node generator back in charge of the
     * TypeScript of the endpoints, which Java writes otherwise:
     * {@code -Dhilla.generator.java=false} runs it over the OpenAPI definition
     * the way every application used to. It goes, along with the Node
     * generator, once nothing needs the way back.
     */
    public static final String JAVA_TYPESCRIPT_PROPERTY = "hilla.generator.java";

    private static final Logger logger = LoggerFactory
            .getLogger(GeneratorProcessor.class);

    private static String TSGEN_PACKAGE_NAME = "@vaadin/hilla-generator-cli";
    private final Path baseDir;
    private final String nodeCommand;
    private final Path openAPIFile;
    private final Path outputDirectory;
    private final GeneratorConfiguration.PluginsProcessor pluginsProcessor = new GeneratorConfiguration.PluginsProcessor();
    private GeneratorConfiguration generatorConfiguration;

    public GeneratorProcessor(EngineAutoConfiguration conf) {
        this.baseDir = conf.getBaseDir();
        this.openAPIFile = conf.getOpenAPIFile();
        this.outputDirectory = conf.getOutputDir();
        this.nodeCommand = conf.getNodeCommand();
        applyConfiguration(conf.getGenerator());
    }

    /**
     * Whether the TypeScript of the endpoints is written in Java, which it is
     * unless a run asks for the Node generator instead. The caller has to know
     * as well: what the Java writers need is what the parser found, and only
     * the run which parsed the classes has it.
     *
     * @see #JAVA_TYPESCRIPT_PROPERTY
     */
    public static boolean writesTypeScriptInJava() {
        return !"false"
                .equalsIgnoreCase(System.getProperty(JAVA_TYPESCRIPT_PROPERTY));
    }

    /**
     * Generates the TypeScript of the endpoints out of what a run of the parser
     * found, unless the Node generator is still the one writing it, and then
     * out of the OpenAPI definition that run left behind.
     *
     * @param parser
     *            the run, which has to have happened already
     */
    public void process(ParserProcessor parser) throws GeneratorException {
        if (writesTypeScriptInJava() && !hasConfiguredPlugins()) {
            new TypeScriptProcessor(baseDir, outputDirectory)
                    .process(parser.getGeneration());
            return;
        }

        process();
    }

    /**
     * Whether the application says which plugins to generate with, which only
     * the Node generator knows what to do with: a run of it is what such an
     * application gets, whoever writes the TypeScript otherwise.
     */
    private boolean hasConfiguredPlugins() {
        var plugins = generatorConfiguration == null ? Optional
                .<GeneratorConfiguration.Plugins> empty()
                : generatorConfiguration.getPlugins();

        if (plugins.isEmpty()) {
            return false;
        }

        logger.info("The TypeScript of the endpoints is generated by Node,"
                + " which is what the plugins of the configuration are for.");

        return true;
    }

    public void process() throws GeneratorException {
        if (isOpenAPIEmpty()) {
            cleanup();
            return;
        }

        var arguments = new ArrayList<>();
        arguments.add(getTsgenPath());
        prepareOpenAPI(arguments);
        prepareOutputDir(arguments);
        preparePlugins(arguments);
        prepareVerbose(arguments);

        try {
            var runner = new GeneratorShellRunner(baseDir.toFile(), nodeCommand,
                    arguments.stream().map(Objects::toString)
                            .toArray(String[]::new));
            runner.run(null);
        } catch (LambdaException e) {
            throw new GeneratorException("Node execution failed", e.getCause());
        } catch (CommandNotFoundException e) {
            throw new GeneratorException("Node command not found", e);
        } catch (CommandRunnerException e) {
            throw new GeneratorException("Node execution failed", e);
        }
    }

    /**
     * Removes what a run before this one generated, which is what a generation
     * of nothing leaves behind: the folder is written by both generators, so
     * they clear it the same way.
     */
    private void cleanup() throws GeneratorException {
        logger.debug("Cleaning up old output.");

        try {
            new OutputFolder(outputDirectory).write(List.of());
        } catch (IOException e) {
            throw new GeneratorException("Unable to cleanup generated files",
                    e);
        }
    }

    // Used to catch a checked exception in a lambda and handle it after
    private static class LambdaException extends RuntimeException {
        public LambdaException(Throwable cause) {
            super(cause);
        }
    }

    private GeneratorProcessor applyConfiguration(
            GeneratorConfiguration generatorConfiguration) {
        this.generatorConfiguration = generatorConfiguration;

        if (generatorConfiguration == null) {
            return this;
        }

        generatorConfiguration.getPlugins().ifPresent(this::applyPlugins);
        return this;
    }

    private void applyPlugins(GeneratorConfiguration.@NonNull Plugins plugins) {
        pluginsProcessor.setConfig(plugins);
    }

    private void prepareOpenAPI(ArrayList<Object> arguments) {
        logger.debug("Using OpenAPI file: {}", openAPIFile);
        arguments.add(openAPIFile);
    }

    private void prepareOutputDir(List<Object> arguments) {
        var result = outputDirectory.isAbsolute() ? outputDirectory
                : baseDir.resolve(outputDirectory);
        arguments.add("-o");
        arguments.add(result);
    }

    private void preparePlugins(List<Object> arguments) {
        pluginsProcessor.process().stream()
                .map(GeneratorConfiguration.Plugin::getPath).distinct()
                .forEachOrdered(path -> {
                    arguments.add("-p");
                    arguments.add(path);
                });
    }

    private void prepareVerbose(List<Object> arguments) {
        if (logger.isDebugEnabled()) {
            arguments.add("-v");
        }
    }

    private OpenAPI getOpenAPI() throws IOException {
        String source = Files.readString(openAPIFile);
        var mapper = OpenAPIFileType.JSON.getMapper();
        var reader = mapper.readerFor(OpenAPI.class);
        return reader.readValue(source);
    }

    private boolean isOpenAPIEmpty() {
        try {
            var openApi = getOpenAPI();
            return (openApi.getPaths() == null || openApi.getPaths().isEmpty())
                    && (openApi.getComponents() == null
                            || openApi.getComponents().getSchemas() == null
                            || openApi.getComponents().getSchemas().isEmpty());
        } catch (IOException e) {
            throw new GeneratorException("Unable to read OpenAPI json file", e);
        }
    }

    private Path getTsgenPath() {
        var arguments = List.<String> of("--input-type", "commonjs", "--eval",
                "console.log(require.resolve('" + TSGEN_PACKAGE_NAME + "'))")
                .toArray(String[]::new);
        AtomicReference<String> pathLine = new AtomicReference<>();
        try {
            var runner = new GeneratorShellRunner(baseDir.toFile(), nodeCommand,
                    arguments);
            runner.run(null, (stdOutStream) -> {
                new BufferedReader(new InputStreamReader(stdOutStream)).lines()
                        .limit(1).forEach(pathLine::set);
            }, null);
            if (pathLine.get() == null) {
                throw new CommandRunnerException("No output from Node");
            }
            return Path.of(pathLine.get());
        } catch (LambdaException e) {
            throw new GeneratorException("Node execution failed", e.getCause());
        } catch (CommandNotFoundException e) {
            throw new GeneratorException("Node command not found", e);
        } catch (CommandRunnerException e) {
            throw new GeneratorException("Unable to resolve npm package \""
                    + TSGEN_PACKAGE_NAME + "\"", e);
        }
    }
}
