import { dirname, join } from 'node:path';
import ts from '@typescript/typescript6';

const TYPE_CHECK_OPTIONS: ts.CompilerOptions = {
  module: ts.ModuleKind.ESNext,
  moduleResolution: ts.ModuleResolutionKind.Bundler,
  noEmit: true,
  // the generated sources must not leave imports behind
  noUnusedLocals: true,
  skipLibCheck: true,
  strict: true,
  target: ts.ScriptTarget.ES2022,
};

// the client module is generated by another plugin, which is not part of the
// plugin tests
const CLIENT_STUB = [
  'declare const client: {',
  '  call(endpoint: string, method: string, params?: unknown, init?: unknown): Promise<never>;',
  '};',
  'export default client;',
].join('\n');

/**
 * Type-checks the generated sources, together with the given extra sources,
 * which can be used to assert that the generated types are actually usable.
 * The sources are compiled from memory.
 *
 * @param root - the directory to compile the sources in. It has to be inside
 * the package under test, so that the imported Hilla packages resolve the way
 * they do for that package.
 * @param files - the generated sources
 * @param extraSources - additional sources, by file name relative to `root`
 * @returns the compiler diagnostics, as readable messages
 */
export async function typeCheck(
  root: string,
  files: readonly File[],
  extraSources: Readonly<Record<string, string>> = {},
): Promise<readonly string[]> {
  const sources = new Map<string, string>([[join(root, 'connect-client.default.ts'), CLIENT_STUB]]);

  await Promise.all(files.map(async (file) => sources.set(join(root, file.name), await file.text())));
  Object.entries(extraSources).forEach(([name, content]) => sources.set(join(root, name), content));

  const directories = new Set<string>();
  sources.forEach((_, file) => {
    for (let dir = dirname(file); !directories.has(dir); dir = dirname(dir)) {
      directories.add(dir);
    }
  });

  const host = ts.createCompilerHost(TYPE_CHECK_OPTIONS, true);
  const directoryExists = host.directoryExists?.bind(host);
  const fileExists = host.fileExists.bind(host);
  const getSourceFile = host.getSourceFile.bind(host);
  const hostReadFile = host.readFile.bind(host);
  const realpath = host.realpath?.bind(host);

  host.fileExists = (file) => sources.has(file) || fileExists(file);
  host.readFile = (file) => sources.get(file) ?? hostReadFile(file);
  host.directoryExists = (dir) => directories.has(dir) || (directoryExists?.(dir) ?? false);
  host.realpath = (file) => (sources.has(file) ? file : (realpath?.(file) ?? file));
  host.getSourceFile = (file, languageVersion, onError, shouldCreate) => {
    const source = sources.get(file);
    return source === undefined
      ? getSourceFile(file, languageVersion, onError, shouldCreate)
      : ts.createSourceFile(file, source, languageVersion, true);
  };

  const program = ts.createProgram([...sources.keys()], TYPE_CHECK_OPTIONS, host);
  const prefix = `${root}/`;

  return ts
    .getPreEmitDiagnostics(program)
    .filter((diagnostic) => !diagnostic.file || sources.has(diagnostic.file.fileName))
    .map((diagnostic) => {
      const name = diagnostic.file?.fileName.replace(prefix, '') ?? '';
      const message = ts.flattenDiagnosticMessageText(diagnostic.messageText, ' ');

      return `${name}: ${message}`;
    });
}
